name: On Issue Creation
run-name: ${{ github.actor }} creates an issue ${{ github.event.issue.title }}
on:
  issues:
    types: [opened]
    run: |
        echo "Issue id: ${{ github.event.issue.id }}"
        echo "Issue number: ${{ github.event.issue.number }}"
        echo "Issue title: ${{ github.event.issue.title }}"
        echo "Issue body: ${{ github.event.issue.body }}"